### ISSUE TITLE
Got unexpected extra argument (Tips)

### ISSUE THREAD

**Issue by Olmo-Gutierrez** [JJTech0130/TrollRestore#11]
PS C:\Users\olmor\Documents\Projects\ios17\TrollRestore> python3 trollstore.py Tips
Got unexpected extra argument (Tips)
Usage:  [OPTIONS]

Options:
  --rsd <TEXT INTEGER>...  RSD hostname and port number (as provided by a `start-tunnel` subcommand).
                           NOTE: This argument is mutually exclusive with  arguments: [rsd_service_provider_using_tunneld].
  --tunnel TEXT            Either an empty string to force tunneld device selection, or a UDID of a tunneld discovered device.
                           The string may be suffixed with :PORT in case tunneld is not serving at the default port.
                           NOTE: This argument is mutually exclusive with  arguments: [rsd_service_provider_manually].
  --usbmux TEXT            usbmuxd listener address (in the form of either
                           /path/to/unix/socket OR HOST:PORT
  --udid TEXT              Device unique identifier. You may pass
                           PYMOBILEDEVICE3_UDID environment variable to pass
                           this option as well
  -v, --verbose
  -v, --verbose
  --color / --no-color     colorize output
  --help                   Show this message and exit.

**Comment by alfiecg24** [comment]
Simply use `python3 trollstore.py`
