### ISSUE TITLE
iOS 16.7.2 (20H115) is not supported.

### ISSUE THREAD

**Issue by Carlos-matches** [JJTech0130/TrollRestore#12]
iOS 16.7.2 (20H115) is not supported.

**Comment by gamer191** [comment]
Courtesy of https://ios.cfw.guide/installing-trollstore/
> If your device is on iOS 14.0 beta 1 or earlier, is running iOS 16.7.x (excluding 16.7 RC (20H18)), or is running iOS 17.0.1 or newer, it will never be supported by TrollStore.
