### ISSUE TITLE
Click module problem

### ISSUE THREAD

**Issue by davecarrijo** [JJTech0130/TrollRestore#13]
<img width="759" alt="SCR-20240904-goys" src="https://github.com/user-attachments/assets/93dfcb89-db88-4c39-93ab-b229f09ae27a">

**Comment by cursefroge** [comment]
`pip install click`

**Comment by davecarrijo** [comment]
In fact I did it, pip install click and pip3 install click, both said click is installed the problem persist.

**Comment by da-vinci-noob** [comment]
Create venv.

```
1. python3 -m venv .
2. source bin/activate
3. pip install -r requirements.txt
4. python trollstore.py
```
