### ISSUE TITLE
Issue with Windows USB

### ISSUE THREAD

**Issue by owenibar** [JJTech0130/TrollRestore#5]
![image](https://github.com/user-attachments/assets/c1d73118-7e56-475c-8081-3eeafc607aec)

Please look into this, computer is trusted and device is connected via USB.

**Comment by verygenericname** [comment]
Did you trust your computer?

**Comment by owenibar** [comment]
Yes

**Comment by verygenericname** [comment]
Does iTunes show the device in the list, maybe if iTunes is open close it?

**Comment by verygenericname** [comment]
Install itunes from here: https://www.apple.com/itunes/download/win64/
and try again.

**Comment by owenibar** [comment]
That worked, thanks!
